// Code generated by ent, DO NOT EDIT.

package productitem

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/faysalahmed-dev/wherehouse-order-picklist/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.ProductItem {
	return predicate.ProductItem(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.ProductItem {
	return predicate.ProductItem(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.ProductItem {
	return predicate.ProductItem(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.ProductItem {
	return predicate.ProductItem(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.ProductItem {
	return predicate.ProductItem(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.ProductItem {
	return predicate.ProductItem(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.ProductItem {
	return predicate.ProductItem(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.ProductItem {
	return predicate.ProductItem(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.ProductItem {
	return predicate.ProductItem(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.ProductItem {
	return predicate.ProductItem(sql.FieldEQ(FieldName, v))
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v string) predicate.ProductItem {
	return predicate.ProductItem(sql.FieldEQ(FieldAmount, v))
}

// UnitType applies equality check predicate on the "unit_type" field. It's identical to UnitTypeEQ.
func UnitType(v string) predicate.ProductItem {
	return predicate.ProductItem(sql.FieldEQ(FieldUnitType, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ProductItem {
	return predicate.ProductItem(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ProductItem {
	return predicate.ProductItem(sql.FieldEQ(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.ProductItem {
	return predicate.ProductItem(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.ProductItem {
	return predicate.ProductItem(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.ProductItem {
	return predicate.ProductItem(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.ProductItem {
	return predicate.ProductItem(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.ProductItem {
	return predicate.ProductItem(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.ProductItem {
	return predicate.ProductItem(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.ProductItem {
	return predicate.ProductItem(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.ProductItem {
	return predicate.ProductItem(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.ProductItem {
	return predicate.ProductItem(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.ProductItem {
	return predicate.ProductItem(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.ProductItem {
	return predicate.ProductItem(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.ProductItem {
	return predicate.ProductItem(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.ProductItem {
	return predicate.ProductItem(sql.FieldContainsFold(FieldName, v))
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v string) predicate.ProductItem {
	return predicate.ProductItem(sql.FieldEQ(FieldAmount, v))
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v string) predicate.ProductItem {
	return predicate.ProductItem(sql.FieldNEQ(FieldAmount, v))
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...string) predicate.ProductItem {
	return predicate.ProductItem(sql.FieldIn(FieldAmount, vs...))
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...string) predicate.ProductItem {
	return predicate.ProductItem(sql.FieldNotIn(FieldAmount, vs...))
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v string) predicate.ProductItem {
	return predicate.ProductItem(sql.FieldGT(FieldAmount, v))
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v string) predicate.ProductItem {
	return predicate.ProductItem(sql.FieldGTE(FieldAmount, v))
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v string) predicate.ProductItem {
	return predicate.ProductItem(sql.FieldLT(FieldAmount, v))
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v string) predicate.ProductItem {
	return predicate.ProductItem(sql.FieldLTE(FieldAmount, v))
}

// AmountContains applies the Contains predicate on the "amount" field.
func AmountContains(v string) predicate.ProductItem {
	return predicate.ProductItem(sql.FieldContains(FieldAmount, v))
}

// AmountHasPrefix applies the HasPrefix predicate on the "amount" field.
func AmountHasPrefix(v string) predicate.ProductItem {
	return predicate.ProductItem(sql.FieldHasPrefix(FieldAmount, v))
}

// AmountHasSuffix applies the HasSuffix predicate on the "amount" field.
func AmountHasSuffix(v string) predicate.ProductItem {
	return predicate.ProductItem(sql.FieldHasSuffix(FieldAmount, v))
}

// AmountEqualFold applies the EqualFold predicate on the "amount" field.
func AmountEqualFold(v string) predicate.ProductItem {
	return predicate.ProductItem(sql.FieldEqualFold(FieldAmount, v))
}

// AmountContainsFold applies the ContainsFold predicate on the "amount" field.
func AmountContainsFold(v string) predicate.ProductItem {
	return predicate.ProductItem(sql.FieldContainsFold(FieldAmount, v))
}

// UnitTypeEQ applies the EQ predicate on the "unit_type" field.
func UnitTypeEQ(v string) predicate.ProductItem {
	return predicate.ProductItem(sql.FieldEQ(FieldUnitType, v))
}

// UnitTypeNEQ applies the NEQ predicate on the "unit_type" field.
func UnitTypeNEQ(v string) predicate.ProductItem {
	return predicate.ProductItem(sql.FieldNEQ(FieldUnitType, v))
}

// UnitTypeIn applies the In predicate on the "unit_type" field.
func UnitTypeIn(vs ...string) predicate.ProductItem {
	return predicate.ProductItem(sql.FieldIn(FieldUnitType, vs...))
}

// UnitTypeNotIn applies the NotIn predicate on the "unit_type" field.
func UnitTypeNotIn(vs ...string) predicate.ProductItem {
	return predicate.ProductItem(sql.FieldNotIn(FieldUnitType, vs...))
}

// UnitTypeGT applies the GT predicate on the "unit_type" field.
func UnitTypeGT(v string) predicate.ProductItem {
	return predicate.ProductItem(sql.FieldGT(FieldUnitType, v))
}

// UnitTypeGTE applies the GTE predicate on the "unit_type" field.
func UnitTypeGTE(v string) predicate.ProductItem {
	return predicate.ProductItem(sql.FieldGTE(FieldUnitType, v))
}

// UnitTypeLT applies the LT predicate on the "unit_type" field.
func UnitTypeLT(v string) predicate.ProductItem {
	return predicate.ProductItem(sql.FieldLT(FieldUnitType, v))
}

// UnitTypeLTE applies the LTE predicate on the "unit_type" field.
func UnitTypeLTE(v string) predicate.ProductItem {
	return predicate.ProductItem(sql.FieldLTE(FieldUnitType, v))
}

// UnitTypeContains applies the Contains predicate on the "unit_type" field.
func UnitTypeContains(v string) predicate.ProductItem {
	return predicate.ProductItem(sql.FieldContains(FieldUnitType, v))
}

// UnitTypeHasPrefix applies the HasPrefix predicate on the "unit_type" field.
func UnitTypeHasPrefix(v string) predicate.ProductItem {
	return predicate.ProductItem(sql.FieldHasPrefix(FieldUnitType, v))
}

// UnitTypeHasSuffix applies the HasSuffix predicate on the "unit_type" field.
func UnitTypeHasSuffix(v string) predicate.ProductItem {
	return predicate.ProductItem(sql.FieldHasSuffix(FieldUnitType, v))
}

// UnitTypeEqualFold applies the EqualFold predicate on the "unit_type" field.
func UnitTypeEqualFold(v string) predicate.ProductItem {
	return predicate.ProductItem(sql.FieldEqualFold(FieldUnitType, v))
}

// UnitTypeContainsFold applies the ContainsFold predicate on the "unit_type" field.
func UnitTypeContainsFold(v string) predicate.ProductItem {
	return predicate.ProductItem(sql.FieldContainsFold(FieldUnitType, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ProductItem {
	return predicate.ProductItem(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ProductItem {
	return predicate.ProductItem(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ProductItem {
	return predicate.ProductItem(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ProductItem {
	return predicate.ProductItem(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ProductItem {
	return predicate.ProductItem(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ProductItem {
	return predicate.ProductItem(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ProductItem {
	return predicate.ProductItem(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ProductItem {
	return predicate.ProductItem(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ProductItem {
	return predicate.ProductItem(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ProductItem {
	return predicate.ProductItem(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ProductItem {
	return predicate.ProductItem(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ProductItem {
	return predicate.ProductItem(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ProductItem {
	return predicate.ProductItem(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ProductItem {
	return predicate.ProductItem(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ProductItem {
	return predicate.ProductItem(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ProductItem {
	return predicate.ProductItem(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasSubCategories applies the HasEdge predicate on the "sub_categories" edge.
func HasSubCategories() predicate.ProductItem {
	return predicate.ProductItem(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SubCategoriesTable, SubCategoriesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSubCategoriesWith applies the HasEdge predicate on the "sub_categories" edge with a given conditions (other predicates).
func HasSubCategoriesWith(preds ...predicate.SubCategory) predicate.ProductItem {
	return predicate.ProductItem(func(s *sql.Selector) {
		step := newSubCategoriesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.ProductItem {
	return predicate.ProductItem(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.ProductItem {
	return predicate.ProductItem(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ProductItem) predicate.ProductItem {
	return predicate.ProductItem(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ProductItem) predicate.ProductItem {
	return predicate.ProductItem(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ProductItem) predicate.ProductItem {
	return predicate.ProductItem(sql.NotPredicates(p))
}
