// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/faysalahmed-dev/wherehouse-order-picklist/ent/order"
	"github.com/faysalahmed-dev/wherehouse-order-picklist/ent/predicate"
	"github.com/faysalahmed-dev/wherehouse-order-picklist/ent/productitem"
	"github.com/faysalahmed-dev/wherehouse-order-picklist/ent/subcategory"
	"github.com/faysalahmed-dev/wherehouse-order-picklist/ent/user"
	"github.com/google/uuid"
)

// ProductItemQuery is the builder for querying ProductItem entities.
type ProductItemQuery struct {
	config
	ctx               *QueryContext
	order             []productitem.OrderOption
	inters            []Interceptor
	predicates        []predicate.ProductItem
	withSubCategories *SubCategoryQuery
	withOrder         *OrderQuery
	withUser          *UserQuery
	withFKs           bool
	modifiers         []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ProductItemQuery builder.
func (piq *ProductItemQuery) Where(ps ...predicate.ProductItem) *ProductItemQuery {
	piq.predicates = append(piq.predicates, ps...)
	return piq
}

// Limit the number of records to be returned by this query.
func (piq *ProductItemQuery) Limit(limit int) *ProductItemQuery {
	piq.ctx.Limit = &limit
	return piq
}

// Offset to start from.
func (piq *ProductItemQuery) Offset(offset int) *ProductItemQuery {
	piq.ctx.Offset = &offset
	return piq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (piq *ProductItemQuery) Unique(unique bool) *ProductItemQuery {
	piq.ctx.Unique = &unique
	return piq
}

// Order specifies how the records should be ordered.
func (piq *ProductItemQuery) Order(o ...productitem.OrderOption) *ProductItemQuery {
	piq.order = append(piq.order, o...)
	return piq
}

// QuerySubCategories chains the current query on the "sub_categories" edge.
func (piq *ProductItemQuery) QuerySubCategories() *SubCategoryQuery {
	query := (&SubCategoryClient{config: piq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := piq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := piq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(productitem.Table, productitem.FieldID, selector),
			sqlgraph.To(subcategory.Table, subcategory.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, productitem.SubCategoriesTable, productitem.SubCategoriesColumn),
		)
		fromU = sqlgraph.SetNeighbors(piq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryOrder chains the current query on the "order" edge.
func (piq *ProductItemQuery) QueryOrder() *OrderQuery {
	query := (&OrderClient{config: piq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := piq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := piq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(productitem.Table, productitem.FieldID, selector),
			sqlgraph.To(order.Table, order.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, productitem.OrderTable, productitem.OrderColumn),
		)
		fromU = sqlgraph.SetNeighbors(piq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryUser chains the current query on the "user" edge.
func (piq *ProductItemQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: piq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := piq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := piq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(productitem.Table, productitem.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, productitem.UserTable, productitem.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(piq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ProductItem entity from the query.
// Returns a *NotFoundError when no ProductItem was found.
func (piq *ProductItemQuery) First(ctx context.Context) (*ProductItem, error) {
	nodes, err := piq.Limit(1).All(setContextOp(ctx, piq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{productitem.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (piq *ProductItemQuery) FirstX(ctx context.Context) *ProductItem {
	node, err := piq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ProductItem ID from the query.
// Returns a *NotFoundError when no ProductItem ID was found.
func (piq *ProductItemQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = piq.Limit(1).IDs(setContextOp(ctx, piq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{productitem.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (piq *ProductItemQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := piq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ProductItem entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ProductItem entity is found.
// Returns a *NotFoundError when no ProductItem entities are found.
func (piq *ProductItemQuery) Only(ctx context.Context) (*ProductItem, error) {
	nodes, err := piq.Limit(2).All(setContextOp(ctx, piq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{productitem.Label}
	default:
		return nil, &NotSingularError{productitem.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (piq *ProductItemQuery) OnlyX(ctx context.Context) *ProductItem {
	node, err := piq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ProductItem ID in the query.
// Returns a *NotSingularError when more than one ProductItem ID is found.
// Returns a *NotFoundError when no entities are found.
func (piq *ProductItemQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = piq.Limit(2).IDs(setContextOp(ctx, piq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{productitem.Label}
	default:
		err = &NotSingularError{productitem.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (piq *ProductItemQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := piq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ProductItems.
func (piq *ProductItemQuery) All(ctx context.Context) ([]*ProductItem, error) {
	ctx = setContextOp(ctx, piq.ctx, "All")
	if err := piq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ProductItem, *ProductItemQuery]()
	return withInterceptors[[]*ProductItem](ctx, piq, qr, piq.inters)
}

// AllX is like All, but panics if an error occurs.
func (piq *ProductItemQuery) AllX(ctx context.Context) []*ProductItem {
	nodes, err := piq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ProductItem IDs.
func (piq *ProductItemQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if piq.ctx.Unique == nil && piq.path != nil {
		piq.Unique(true)
	}
	ctx = setContextOp(ctx, piq.ctx, "IDs")
	if err = piq.Select(productitem.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (piq *ProductItemQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := piq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (piq *ProductItemQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, piq.ctx, "Count")
	if err := piq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, piq, querierCount[*ProductItemQuery](), piq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (piq *ProductItemQuery) CountX(ctx context.Context) int {
	count, err := piq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (piq *ProductItemQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, piq.ctx, "Exist")
	switch _, err := piq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (piq *ProductItemQuery) ExistX(ctx context.Context) bool {
	exist, err := piq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ProductItemQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (piq *ProductItemQuery) Clone() *ProductItemQuery {
	if piq == nil {
		return nil
	}
	return &ProductItemQuery{
		config:            piq.config,
		ctx:               piq.ctx.Clone(),
		order:             append([]productitem.OrderOption{}, piq.order...),
		inters:            append([]Interceptor{}, piq.inters...),
		predicates:        append([]predicate.ProductItem{}, piq.predicates...),
		withSubCategories: piq.withSubCategories.Clone(),
		withOrder:         piq.withOrder.Clone(),
		withUser:          piq.withUser.Clone(),
		// clone intermediate query.
		sql:  piq.sql.Clone(),
		path: piq.path,
	}
}

// WithSubCategories tells the query-builder to eager-load the nodes that are connected to
// the "sub_categories" edge. The optional arguments are used to configure the query builder of the edge.
func (piq *ProductItemQuery) WithSubCategories(opts ...func(*SubCategoryQuery)) *ProductItemQuery {
	query := (&SubCategoryClient{config: piq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	piq.withSubCategories = query
	return piq
}

// WithOrder tells the query-builder to eager-load the nodes that are connected to
// the "order" edge. The optional arguments are used to configure the query builder of the edge.
func (piq *ProductItemQuery) WithOrder(opts ...func(*OrderQuery)) *ProductItemQuery {
	query := (&OrderClient{config: piq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	piq.withOrder = query
	return piq
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (piq *ProductItemQuery) WithUser(opts ...func(*UserQuery)) *ProductItemQuery {
	query := (&UserClient{config: piq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	piq.withUser = query
	return piq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ProductItem.Query().
//		GroupBy(productitem.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (piq *ProductItemQuery) GroupBy(field string, fields ...string) *ProductItemGroupBy {
	piq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ProductItemGroupBy{build: piq}
	grbuild.flds = &piq.ctx.Fields
	grbuild.label = productitem.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name"`
//	}
//
//	client.ProductItem.Query().
//		Select(productitem.FieldName).
//		Scan(ctx, &v)
func (piq *ProductItemQuery) Select(fields ...string) *ProductItemSelect {
	piq.ctx.Fields = append(piq.ctx.Fields, fields...)
	sbuild := &ProductItemSelect{ProductItemQuery: piq}
	sbuild.label = productitem.Label
	sbuild.flds, sbuild.scan = &piq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ProductItemSelect configured with the given aggregations.
func (piq *ProductItemQuery) Aggregate(fns ...AggregateFunc) *ProductItemSelect {
	return piq.Select().Aggregate(fns...)
}

func (piq *ProductItemQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range piq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, piq); err != nil {
				return err
			}
		}
	}
	for _, f := range piq.ctx.Fields {
		if !productitem.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if piq.path != nil {
		prev, err := piq.path(ctx)
		if err != nil {
			return err
		}
		piq.sql = prev
	}
	return nil
}

func (piq *ProductItemQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ProductItem, error) {
	var (
		nodes       = []*ProductItem{}
		withFKs     = piq.withFKs
		_spec       = piq.querySpec()
		loadedTypes = [3]bool{
			piq.withSubCategories != nil,
			piq.withOrder != nil,
			piq.withUser != nil,
		}
	)
	if piq.withSubCategories != nil || piq.withOrder != nil || piq.withUser != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, productitem.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ProductItem).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ProductItem{config: piq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(piq.modifiers) > 0 {
		_spec.Modifiers = piq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, piq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := piq.withSubCategories; query != nil {
		if err := piq.loadSubCategories(ctx, query, nodes, nil,
			func(n *ProductItem, e *SubCategory) { n.Edges.SubCategories = e }); err != nil {
			return nil, err
		}
	}
	if query := piq.withOrder; query != nil {
		if err := piq.loadOrder(ctx, query, nodes, nil,
			func(n *ProductItem, e *Order) { n.Edges.Order = e }); err != nil {
			return nil, err
		}
	}
	if query := piq.withUser; query != nil {
		if err := piq.loadUser(ctx, query, nodes, nil,
			func(n *ProductItem, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (piq *ProductItemQuery) loadSubCategories(ctx context.Context, query *SubCategoryQuery, nodes []*ProductItem, init func(*ProductItem), assign func(*ProductItem, *SubCategory)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*ProductItem)
	for i := range nodes {
		if nodes[i].sub_category_product_items == nil {
			continue
		}
		fk := *nodes[i].sub_category_product_items
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(subcategory.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "sub_category_product_items" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (piq *ProductItemQuery) loadOrder(ctx context.Context, query *OrderQuery, nodes []*ProductItem, init func(*ProductItem), assign func(*ProductItem, *Order)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*ProductItem)
	for i := range nodes {
		if nodes[i].order_product == nil {
			continue
		}
		fk := *nodes[i].order_product
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(order.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "order_product" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (piq *ProductItemQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*ProductItem, init func(*ProductItem), assign func(*ProductItem, *User)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*ProductItem)
	for i := range nodes {
		if nodes[i].user_product_items == nil {
			continue
		}
		fk := *nodes[i].user_product_items
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_product_items" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (piq *ProductItemQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := piq.querySpec()
	if len(piq.modifiers) > 0 {
		_spec.Modifiers = piq.modifiers
	}
	_spec.Node.Columns = piq.ctx.Fields
	if len(piq.ctx.Fields) > 0 {
		_spec.Unique = piq.ctx.Unique != nil && *piq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, piq.driver, _spec)
}

func (piq *ProductItemQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(productitem.Table, productitem.Columns, sqlgraph.NewFieldSpec(productitem.FieldID, field.TypeUUID))
	_spec.From = piq.sql
	if unique := piq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if piq.path != nil {
		_spec.Unique = true
	}
	if fields := piq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, productitem.FieldID)
		for i := range fields {
			if fields[i] != productitem.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := piq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := piq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := piq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := piq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (piq *ProductItemQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(piq.driver.Dialect())
	t1 := builder.Table(productitem.Table)
	columns := piq.ctx.Fields
	if len(columns) == 0 {
		columns = productitem.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if piq.sql != nil {
		selector = piq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if piq.ctx.Unique != nil && *piq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range piq.modifiers {
		m(selector)
	}
	for _, p := range piq.predicates {
		p(selector)
	}
	for _, p := range piq.order {
		p(selector)
	}
	if offset := piq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := piq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (piq *ProductItemQuery) Modify(modifiers ...func(s *sql.Selector)) *ProductItemSelect {
	piq.modifiers = append(piq.modifiers, modifiers...)
	return piq.Select()
}

// ProductItemGroupBy is the group-by builder for ProductItem entities.
type ProductItemGroupBy struct {
	selector
	build *ProductItemQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (pigb *ProductItemGroupBy) Aggregate(fns ...AggregateFunc) *ProductItemGroupBy {
	pigb.fns = append(pigb.fns, fns...)
	return pigb
}

// Scan applies the selector query and scans the result into the given value.
func (pigb *ProductItemGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pigb.build.ctx, "GroupBy")
	if err := pigb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ProductItemQuery, *ProductItemGroupBy](ctx, pigb.build, pigb, pigb.build.inters, v)
}

func (pigb *ProductItemGroupBy) sqlScan(ctx context.Context, root *ProductItemQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(pigb.fns))
	for _, fn := range pigb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*pigb.flds)+len(pigb.fns))
		for _, f := range *pigb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*pigb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pigb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ProductItemSelect is the builder for selecting fields of ProductItem entities.
type ProductItemSelect struct {
	*ProductItemQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (pis *ProductItemSelect) Aggregate(fns ...AggregateFunc) *ProductItemSelect {
	pis.fns = append(pis.fns, fns...)
	return pis
}

// Scan applies the selector query and scans the result into the given value.
func (pis *ProductItemSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, pis.ctx, "Select")
	if err := pis.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ProductItemQuery, *ProductItemSelect](ctx, pis.ProductItemQuery, pis, pis.inters, v)
}

func (pis *ProductItemSelect) sqlScan(ctx context.Context, root *ProductItemQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(pis.fns))
	for _, fn := range pis.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*pis.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pis.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (pis *ProductItemSelect) Modify(modifiers ...func(s *sql.Selector)) *ProductItemSelect {
	pis.modifiers = append(pis.modifiers, modifiers...)
	return pis
}
