// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/faysalahmed-dev/wherehouse-order-picklist/ent/category"
	"github.com/faysalahmed-dev/wherehouse-order-picklist/ent/subcategory"
	"github.com/faysalahmed-dev/wherehouse-order-picklist/ent/user"
	"github.com/google/uuid"
)

// SubCategory is the model entity for the SubCategory schema.
type SubCategory struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id"`
	// Name holds the value of the "name" field.
	Name string `json:"name"`
	// Descriptions holds the value of the "descriptions" field.
	Descriptions string `json:"descriptions"`
	// Value holds the value of the "value" field.
	Value string `json:"value"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SubCategoryQuery when eager-loading is set.
	Edges                   SubCategoryEdges `json:"edges"`
	category_sub_categories *uuid.UUID
	user_sub_categories     *uuid.UUID
	selectValues            sql.SelectValues
}

// SubCategoryEdges holds the relations/edges for other nodes in the graph.
type SubCategoryEdges struct {
	// ProductItems holds the value of the product_items edge.
	ProductItems []*ProductItem `json:"product_items,omitempty"`
	// Category holds the value of the category edge.
	Category *Category `json:"category,omitempty"`
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// ProductItemsOrErr returns the ProductItems value or an error if the edge
// was not loaded in eager-loading.
func (e SubCategoryEdges) ProductItemsOrErr() ([]*ProductItem, error) {
	if e.loadedTypes[0] {
		return e.ProductItems, nil
	}
	return nil, &NotLoadedError{edge: "product_items"}
}

// CategoryOrErr returns the Category value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SubCategoryEdges) CategoryOrErr() (*Category, error) {
	if e.loadedTypes[1] {
		if e.Category == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: category.Label}
		}
		return e.Category, nil
	}
	return nil, &NotLoadedError{edge: "category"}
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SubCategoryEdges) UserOrErr() (*User, error) {
	if e.loadedTypes[2] {
		if e.User == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: user.Label}
		}
		return e.User, nil
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SubCategory) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case subcategory.FieldName, subcategory.FieldDescriptions, subcategory.FieldValue:
			values[i] = new(sql.NullString)
		case subcategory.FieldCreatedAt, subcategory.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case subcategory.FieldID:
			values[i] = new(uuid.UUID)
		case subcategory.ForeignKeys[0]: // category_sub_categories
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case subcategory.ForeignKeys[1]: // user_sub_categories
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SubCategory fields.
func (sc *SubCategory) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case subcategory.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				sc.ID = *value
			}
		case subcategory.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				sc.Name = value.String
			}
		case subcategory.FieldDescriptions:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field descriptions", values[i])
			} else if value.Valid {
				sc.Descriptions = value.String
			}
		case subcategory.FieldValue:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field value", values[i])
			} else if value.Valid {
				sc.Value = value.String
			}
		case subcategory.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				sc.CreatedAt = value.Time
			}
		case subcategory.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				sc.UpdatedAt = value.Time
			}
		case subcategory.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field category_sub_categories", values[i])
			} else if value.Valid {
				sc.category_sub_categories = new(uuid.UUID)
				*sc.category_sub_categories = *value.S.(*uuid.UUID)
			}
		case subcategory.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field user_sub_categories", values[i])
			} else if value.Valid {
				sc.user_sub_categories = new(uuid.UUID)
				*sc.user_sub_categories = *value.S.(*uuid.UUID)
			}
		default:
			sc.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// GetValue returns the ent.Value that was dynamically selected and assigned to the SubCategory.
// This includes values selected through modifiers, order, etc.
func (sc *SubCategory) GetValue(name string) (ent.Value, error) {
	return sc.selectValues.Get(name)
}

// QueryProductItems queries the "product_items" edge of the SubCategory entity.
func (sc *SubCategory) QueryProductItems() *ProductItemQuery {
	return NewSubCategoryClient(sc.config).QueryProductItems(sc)
}

// QueryCategory queries the "category" edge of the SubCategory entity.
func (sc *SubCategory) QueryCategory() *CategoryQuery {
	return NewSubCategoryClient(sc.config).QueryCategory(sc)
}

// QueryUser queries the "user" edge of the SubCategory entity.
func (sc *SubCategory) QueryUser() *UserQuery {
	return NewSubCategoryClient(sc.config).QueryUser(sc)
}

// Update returns a builder for updating this SubCategory.
// Note that you need to call SubCategory.Unwrap() before calling this method if this SubCategory
// was returned from a transaction, and the transaction was committed or rolled back.
func (sc *SubCategory) Update() *SubCategoryUpdateOne {
	return NewSubCategoryClient(sc.config).UpdateOne(sc)
}

// Unwrap unwraps the SubCategory entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (sc *SubCategory) Unwrap() *SubCategory {
	_tx, ok := sc.config.driver.(*txDriver)
	if !ok {
		panic("ent: SubCategory is not a transactional entity")
	}
	sc.config.driver = _tx.drv
	return sc
}

// String implements the fmt.Stringer.
func (sc *SubCategory) String() string {
	var builder strings.Builder
	builder.WriteString("SubCategory(")
	builder.WriteString(fmt.Sprintf("id=%v, ", sc.ID))
	builder.WriteString("name=")
	builder.WriteString(sc.Name)
	builder.WriteString(", ")
	builder.WriteString("descriptions=")
	builder.WriteString(sc.Descriptions)
	builder.WriteString(", ")
	builder.WriteString("value=")
	builder.WriteString(sc.Value)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(sc.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(sc.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// SubCategories is a parsable slice of SubCategory.
type SubCategories []*SubCategory
